-- MySQL Script generated by MySQL Workbench
-- Thu Apr 20 13:47:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CourseWork
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CourseWork` ;

-- -----------------------------------------------------
-- Schema CourseWork
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CourseWork` DEFAULT CHARACTER SET utf8 ;
USE `CourseWork` ;

-- -----------------------------------------------------
-- Table `CourseWork`.`subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CourseWork`.`subjects` ;

CREATE TABLE IF NOT EXISTS `CourseWork`.`subjects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `course` INT NOT NULL,
  `semester` ENUM('1', '2') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CourseWork`.`teachers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CourseWork`.`teachers` ;

CREATE TABLE IF NOT EXISTS `CourseWork`.`teachers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CourseWork`.`lectures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CourseWork`.`lectures` ;

CREATE TABLE IF NOT EXISTS `CourseWork`.`lectures` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `subjects_id` INT NOT NULL,
  `teachers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lectures_subject_idx` (`subjects_id` ASC) VISIBLE,
  INDEX `fk_lectures_teachers1_idx` (`teachers_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CourseWork`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CourseWork`.`students` ;

CREATE TABLE IF NOT EXISTS `CourseWork`.`students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL,
  `group_num` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CourseWork`.`lectures_has_students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CourseWork`.`lectures_has_students` ;

CREATE TABLE IF NOT EXISTS `CourseWork`.`lectures_has_students` (
  `lectures_id` INT NOT NULL,
  `students_id` INT NOT NULL,
  PRIMARY KEY (`lectures_id`, `students_id`),
  INDEX `fk_lectures_has_students_students1_idx` (`students_id` ASC) VISIBLE,
  INDEX `fk_lectures_has_students_lectures1_idx` (`lectures_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
